name: my_portifolio
description: my portifolio

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  simple_animations: ^2.5.1
  animated_widgets: ^1.0.6
  assets_audio_player: ^2.0.13+8
  splash_screen_view: ^1.0.3
  cached_network_image: ^2.5.0
  carousel_pro: ^1.0.0
  font_awesome_flutter: ^8.11.0
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/meals/
    - assets/images/conews/

  fonts:
    - family: Bebas Neue
      fonts:
        - asset: assets\fonts\BebasNeue-Regular.ttf
    - family: Savings Bond Shadow
      fonts:
        - asset: assets\fonts\Savings Bond Shadow Regular.ttf
    - family: stjedise
      fonts:
        - asset: assets\fonts\stjedise.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #